export const CARGO_TYPES = ['FLYASH', 'COAL', 'BAGGED CEMENT', 'OTHER'];

export const VESSELS_STATUS_LIST = ['PLANNED', 'BERTHED', 'MOORED', 'COMPLETED'] as const;

export const GATE_STATUS_LIST = [
  'PENDING_WBIN',
  'WBIN_DONE',
  'UNLOADING',
  'PENDING_WBOUT',
  'COMPLETED',
] as const;

export const FINANCE_RATES = {
  TERMINAL_CHARGE: 45.42, // Per MT
  HANDLING_CHARGE: 167.65, // Per MT
  BERTHING_CHARGE_PER_SLOT: 3000,
  MOORING_CHARGE_PER_SLOT: 4000,
  TRUCK_ENTRY_CHARGE: 100,
  TRUCK_WEIGHMENT_CHARGE: 250,
  PARKING_CHARGE_PER_TRUCK: 100,
};
